# (generated with --quick)

from typing import Any, Dict, Generator, List, MutableMapping, Set, Tuple

EDITOR_ROLE: str
OWNER_ROLE: str
VIEWER_ROLE: str
_ASSIGNMENT_DEPRECATED_MSG: str
_DICT_ACCESS_MSG: str
_FACTORY_DEPRECATED_MSG: str
collections: module
collections_abc: module
operator: module
warnings: module

class InvalidOperationException(Exception):
    __doc__: str

class Policy(MutableMapping):
    _EDITOR_ROLES: Tuple[str]
    _OWNER_ROLES: Tuple[str]
    _VIEWER_ROLES: Tuple[str]
    __doc__: str
    _bindings: List[Dict[str, Any]]
    bindings: Any
    editors: frozenset
    etag: Any
    owners: frozenset
    version: Any
    viewers: frozenset
    def __check_version__(self) -> None: ...
    def __delitem__(self, key) -> None: ...
    def __getitem__(self, key) -> Set[nothing]: ...
    def __init__(self, etag = ..., version = ...) -> None: ...
    def __iter__(self) -> Generator[nothing, Any, None]: ...
    def __len__(self) -> int: ...
    def __setitem__(self, key, value) -> None: ...
    def _contains_conditions(self) -> bool: ...
    @staticmethod
    def all_users() -> str: ...
    @staticmethod
    def authenticated_users() -> str: ...
    @staticmethod
    def domain(domain) -> str: ...
    @classmethod
    def from_api_repr(cls, resource) -> Any: ...
    @staticmethod
    def group(email) -> str: ...
    @staticmethod
    def service_account(email) -> str: ...
    def to_api_repr(self) -> Dict[str, Any]: ...
    @staticmethod
    def user(email) -> str: ...
